### ISSUE TITLE
Question: Predictable Results

### ISSUE THREAD

**Issue by Aelonath** [bdelespierre/php-kmeans#17]
First: I'm not very into math, so if I don't use the correct words, I'm sorry!

I tried kmeans to cluster coordinates (100 latitude and longitude coordinates) into groups of 4. It seems to work alright, but every time I get a different result. As far as I understand, this is due to some randomness in the initial coordinate that is responsible for the algorithm to cluster things later.

The thing is: as long as the initial coordinate set stays the same (means: no points added, removed or altered) there should be always the same result.

What I try to do is to cluster teams (I have a coordinate for every team) which are distributed over a country. The goal is that teams don't have to travel a long distance to meet in groups to play together, and every team is inside such a group.

Maybe Kmeans is not the right thing to use for this use case? Or there is a solution to get predictable results with this library of yours?

**Comment by bdelespierre** [comment]
I understand your concern.

I [already answered this question here](https://github.com/bdelespierre/php-kmeans/issues/16#issuecomment-855251154) and you'll find a code sample that turns K-Mean into deterministic mode.

Since this is the third occurrence of this question, I think I will update the readme then :joy:
