### ISSUE TITLE
Missing "getPoints" method?

### ISSUE THREAD

**Issue by limelight-dept** [bdelespierre/php-kmeans#8]
I believe the Cluster->getPoints() method is missing within this class. It is referenced within the readme. Am I missing something here?

**Comment by bdelespierre** [comment]
Hi @limelight-dept and thanks for your issue!

You don't really need a Cluster::getPoint method because a cluster is already an iterator over its own points. You can use it like this:

```PHP
foreach ($cluster as $point) {
    var_dump($point->toArray());
}
```

If you really think a Cluster::getPoint method would make it easier, feel free to open a PR, I'll review it :smile:
